package fsml.runtime;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class FsmlSimulator {
  private FsmlObservation fsm;
  public FsmlSimulator(FsmlObservation fsm) {
    this.fsm = fsm;
  }
  public String[] run(String[] input) {
    List<String> output = ListSequence.fromList(new ArrayList<String>());
    String state = fsm.getInitial();
    for (String event : input) {
      String action = fsm.getAction(state, event);
      if (action != null) {
        ListSequence.fromList(output).addElement(action);
      }
      state = fsm.getTarget(state, event);
    }
    return ListSequence.fromList(output).toGenericArray(String.class);
  }
}
