package fsml.runtime;

/*Generated by MPS */


public interface FsmlObservation {
  public String getInitial();
  public String getAction(String state, String event);
  public String getTarget(String state, String event);
}
