package fsml.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class check_State_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_State_NonTypesystemRule() {
  }
  public void applyRule(final SNode state, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    Iterable<SNode> states = SNodeOperations.getNodeDescendants(SNodeOperations.getNodeAncestor(state, MetaAdapterFactory.getConcept(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x6bf90571c2db857fL, "fsml.structure.Fsm"), false, false), MetaAdapterFactory.getConcept(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f453e5c2L, "fsml.structure.State"), false, new SAbstractConcept[]{});
    Iterable<SNode> initials = SNodeOperations.getNodeDescendants(SNodeOperations.getNodeAncestor(state, MetaAdapterFactory.getConcept(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x6bf90571c2db857fL, "fsml.structure.Fsm"), false, false), MetaAdapterFactory.getConcept(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f4546390L, "fsml.structure.Initial"), false, new SAbstractConcept[]{});
    if (Sequence.fromIterable(initials).count() == 0) {
      for (SNode s : Sequence.fromIterable(states)) {
        {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(s, "No initial state defined", "r:ad6fef75-83a6-4dc3-b0fa-1a4cf65e8eba(fsml.typesystem)", "3955953099080066580", null, errorTarget);
        }
      }
    } else if (Sequence.fromIterable(initials).count() > 1) {
      for (SNode s : Sequence.fromIterable(states)) {
        {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(s, "Multiple initial states", "r:ad6fef75-83a6-4dc3-b0fa-1a4cf65e8eba(fsml.typesystem)", "3955953099080182055", null, errorTarget);
        }
      }
    }
    Sequence.fromIterable(states).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        if (it != state && SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) == SPropertyOperations.getString(state, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) {
          {
            MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(it, "Duplicate state " + SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), "r:ad6fef75-83a6-4dc3-b0fa-1a4cf65e8eba(fsml.typesystem)", "4524322011156045704", null, errorTarget);
          }
        }
      }
    });
  }
  public String getApplicableConceptFQName() {
    return "fsml.structure.State";
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConcept().getQualifiedName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }
  public boolean overrides() {
    return false;
  }
}
