package fsml.sandbox;

/*Generated by MPS */

import fsml.runtime.Fsm;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;
import fsml.runtime.State;
import fsml.runtime.Transition;
import fsml.runtime.FsmlSimulator;

public class Sample {

  public static final Fsm SAMPLE = new Fsm(ListSequence.fromListAndArray(new LinkedList<State>(), new State("locked", true), new State("unlocked"), new State("exception")), ListSequence.fromListAndArray(new LinkedList<Transition>(), new Transition("locked", "ticket", "collect", "unlocked"), new Transition("locked", "pass", "alarm", "exception"), new Transition("unlocked", "ticket", "eject", "unlocked"), new Transition("unlocked", "pass", null, "locked"), new Transition("exception", "ticket", "eject", "exception"), new Transition("exception", "pass", null, "exception"), new Transition("exception", "mute", null, "exception"), new Transition("exception", "release", null, "locked")));
  public static void main(String[] args) {
    String[] input = {"ticket", "ticket", "pass", "pass", "ticket", "mute", "release"};
    String[] output = new FsmlSimulator(SAMPLE).run(input);
    System.out.println(String.join(",", output));
  }

}
