package fsml.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 1:
        return new Fsm_BehaviorDescriptor();
      case 4:
        return new State_BehaviorDescriptor();
      case 0:
        return new Action_BehaviorDescriptor();
      case 3:
        return new Input_BehaviorDescriptor();
      case 5:
        return new Transition_BehaviorDescriptor();
      case 2:
        return new Initial_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"fsml.structure.Action", "fsml.structure.Fsm", "fsml.structure.Initial", "fsml.structure.Input", "fsml.structure.State", "fsml.structure.Transition"};
}
