package fsml.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class Fsm_Behavior {
  public static void init(SNode thisNode) {
  }
  public static List<SNode> call_getUnreachableStates_390028413076217865(SNode thisNode) {
    List<SNode> visitedStates = ListSequence.fromList(SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x6bf90571c2db857fL, 0x3ec99ee5f4546874L, "states"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, MetaAdapterFactory.getContainmentLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f453e5c2L, 0x3ec99ee5f4546880L, "initial")) != null);
      }
    }).toListSequence();
    List<SNode> statesToVisit = ListSequence.fromList(visitedStates).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f453e5c2L, 0x3ec99ee5f4546882L, "transitions"));
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f4546367L, 0x3ec99ee5f4546896L, "target")) != null);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f4546367L, 0x3ec99ee5f4546896L, "target"));
      }
    }).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (it != null);
      }
    }).toListSequence();
    return Fsm_Behavior.call_getUnreachableStates_390028413076217805(thisNode, visitedStates, statesToVisit);
  }
  public static List<SNode> call_getUnreachableStates_390028413076217805(SNode thisNode, final List<SNode> visitedStates, List<SNode> statesToVisit) {
    if (LOG.isDebugEnabled()) {
      LOG.debug("visited states: " + IterableUtils.join(ListSequence.fromList(visitedStates).select(new ISelector<SNode, String>() {
        public String select(SNode it) {
          return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
        }
      }), ", "));
    }
    if (LOG.isDebugEnabled()) {
      LOG.debug("states to visit: " + IterableUtils.join(ListSequence.fromList(statesToVisit).select(new ISelector<SNode, String>() {
        public String select(SNode it) {
          return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
        }
      }), ", "));
    }
    if (ListSequence.fromList(statesToVisit).isEmpty()) {
      if (LOG.isDebugEnabled()) {
        LOG.debug("unreachable states: " + IterableUtils.join(ListSequence.fromList(SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x6bf90571c2db857fL, 0x3ec99ee5f4546874L, "states"))).where(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return !(ListSequence.fromList(visitedStates).contains(it));
          }
        }).select(new ISelector<SNode, String>() {
          public String select(SNode it) {
            return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
          }
        }), ", "));
      }
      return ListSequence.fromList(SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x6bf90571c2db857fL, 0x3ec99ee5f4546874L, "states"))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return !(ListSequence.fromList(visitedStates).contains(it));
        }
      }).toListSequence();
    } else {
      return Fsm_Behavior.call_getUnreachableStates_390028413076217805(thisNode, ListSequence.fromList(visitedStates).union(ListSequence.fromList(statesToVisit)).toListSequence(), ListSequence.fromList(statesToVisit).translate(new ITranslator2<SNode, SNode>() {
        public Iterable<SNode> translate(SNode it) {
          return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f453e5c2L, 0x3ec99ee5f4546882L, "transitions"));
        }
      }).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return (SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f4546367L, 0x3ec99ee5f4546896L, "target")) != null);
        }
      }).select(new ISelector<SNode, SNode>() {
        public SNode select(SNode it) {
          return SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0x1e0d5fd6c07a4df5L, 0x9c9bc73735ba6c37L, 0x3ec99ee5f4546367L, 0x3ec99ee5f4546896L, "target"));
        }
      }).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return (it != null) && !(ListSequence.fromList(visitedStates).contains(it));
        }
      }).toListSequence());
    }
  }
  protected static Logger LOG = LogManager.getLogger(Fsm_Behavior.class);
}
