package fsml.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Fsm_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Fsm_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "fsml.structure.Fsm";
  }
}
