package fsml.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Initial_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Initial_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "fsml.structure.Initial";
  }
}
